import type { ReportTemplate, ReportData, ExportFormat } from "../../types/report";

function safe(value: unknown, fallback = "N/A"): string {
  if (value === null || value === undefined) return fallback;
  if (typeof value === "number" && !Number.isFinite(value)) return fallback;
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#x27;");
}

function fmt(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}

function renderJson(data: ReportData): string {
  const output = {
    reportType: "compliance",
    generatedAt: new Date().toISOString(),
    version: "1.0",
    provenance: {
      system: "SpectraX",
      version: "1.0.0",
      dataSource: "on-device pose estimation pipeline",
      generatedBy: data.user?.displayName ?? "anonymous",
    },
    session: {
      exercise: data.session?.exerciseName ?? null,
      duration: data.session?.duration ?? null,
      timestamp: data.session?.timestamp ?? null,
      totalReps: data.session?.totalReps ?? null,
      accuracy: data.session?.accuracy !== undefined ? Math.round(data.session.accuracy * 100) / 100 : null,
      totalScore: data.session?.totalScore ?? null,
      frames: data.session?.totalFrames ?? null,
    },
    formCompliance: data.biomechanics
      ? {
          repCount: data.biomechanics.repScores.length,
          averageScore: Math.round(data.biomechanics.averageScore * 100) / 100,
          scoreDistribution: {
            min: Math.round(data.biomechanics.minScore * 100) / 100,
            max: Math.round(data.biomechanics.maxScore * 100) / 100,
            standardDeviation: calculateStdDev(data.biomechanics.repScores),
          },
          tempoRatio: data.biomechanics.tempoRatio ?? null,
        }
      : null,
    riskAssessment: data.risk
      ? {
          riskIndex: data.risk.riskIndex,
          fatigueIndex: data.risk.fatigueIndex,
          asymmetryScore: data.risk.asymmetryScore,
          snapshots: data.risk.riskHistory.length,
        }
      : null,
    errors: data.session?.mistakes
      ? Object.entries(data.session.mistakes)
          .map(([issue, count]) => ({ issue, count }))
          .sort((a, b) => b.count - a.count)
      : [],
  };
  return JSON.stringify(output, null, 2);
}

function calculateStdDev(values: number[]): number | null {
  if (values.length < 2) return null;
  const mean = values.reduce((a, b) => a + b, 0) / values.length;
  const variance = values.reduce((sum, v) => sum + (v - mean) ** 2, 0) / values.length;
  return Math.round(Math.sqrt(variance) * 100) / 100;
}

function renderMarkdown(data: ReportData): string {
  const s = data.session;
  const accuracy = s?.accuracy !== undefined ? Math.round(s.accuracy * 100) / 100 : null;

  const lines: string[] = [
    `# Compliance & Audit Report`,
    ``,
    `## Data Provenance`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| System | SpectraX |`,
    `| Version | 1.0.0 |`,
    `| Data Source | on-device pose estimation pipeline |`,
    `| Generated By | ${safe(data.user?.displayName ?? "anonymous")} |`,
    `| Generated At | ${new Date().toISOString()} |`,
    ``,
    `## Session Summary`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| Exercise | ${safe(s?.exerciseName)} |`,
    `| Duration | ${fmt(s?.duration ?? 0)} |`,
    `| Timestamp | ${s?.timestamp ? new Date(s.timestamp).toISOString() : "N/A"} |`,
    `| Total Reps | ${safe(s?.totalReps)} |`,
    `| Accuracy | ${accuracy !== null ? accuracy + "%" : "N/A"} |`,
    `| Total Score | ${safe(s?.totalScore)} |`,
    `| Frames Captured | ${safe(s?.totalFrames)} |`,
    ``,
  ];

  if (data.biomechanics) {
    const b = data.biomechanics;
    const stdDev = calculateStdDev(b.repScores);
    lines.push(`## Form Compliance`, ``);
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Reps Evaluated | ${b.repScores.length} |`);
    lines.push(`| Average Score | ${Math.round(b.averageScore * 100) / 100}% |`);
    lines.push(`| Score Range | ${Math.round(b.minScore)}% – ${Math.round(b.maxScore)}% |`);
    if (stdDev !== null) lines.push(`| Score Std Dev | ${stdDev} |`);
    if (b.tempoRatio) lines.push(`| Tempo Ratio | ${safe(b.tempoRatio)} |`);
    lines.push(``);
  }

  if (data.risk) {
    lines.push(`## Risk Assessment`, ``);
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Risk Index | ${Math.round(data.risk.riskIndex)}/100 |`);
    lines.push(`| Fatigue Index | ${Math.round(data.risk.fatigueIndex)}/100 |`);
    lines.push(`| Asymmetry Score | ${Math.round(data.risk.asymmetryScore)}/100 |`);
    lines.push(`| Risk Snapshots | ${data.risk.riskHistory.length} |`);
    lines.push(``);
  }

  const mistakes = s?.mistakes ? Object.entries(s.mistakes).sort((a, b) => b[1] - a[1]) : [];
  if (mistakes.length > 0) {
    lines.push(`## Error Log`, ``);
    lines.push(`| Issue | Count |`);
    lines.push(`|-------|-------|`);
    for (const [msg, count] of mistakes) {
      lines.push(`| ${safe(msg)} | ${count} |`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*SpectraX Compliance Report · ${new Date().toISOString()} · Version 1.0*`);
  lines.push(`*This report is an audit-quality record of on-device pose analysis data.*`);

  return lines.join("\n");
}

function renderHtml(data: ReportData): string {
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Compliance Report — ${safe(data.session?.exerciseName)}</title>
<style>
  body { font-family: 'Georgia', serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; color: #1e293b; background: #fff; }
  h1 { font-size: 1.4rem; border-bottom: 3px double #475569; padding-bottom: 0.4rem; }
  h2 { font-size: 1.1rem; margin-top: 1.5rem; color: #334155; border-bottom: 1px solid #e2e8f0; padding-bottom: 0.25rem; }
  table { width: 100%; border-collapse: collapse; margin: 0.5rem 0; font-size: 0.88rem; }
  th, td { text-align: left; padding: 0.4rem 0.6rem; border: 1px solid #d1d5db; }
  th { background: #f8fafc; font-weight: 600; }
  .badge-pass { color: #16a34a; font-weight: 600; }
  .badge-fail { color: #dc2626; font-weight: 600; }
  footer { margin-top: 2rem; font-size: 0.7rem; color: #94a3b8; border-top: 2px solid #e2e8f0; padding-top: 0.75rem; }
</style></head>
<body>
  <h1>Compliance & Audit Report</h1>
  <p style="color:#64748b;">${safe(data.session?.exerciseName)} — ${fmt(data.session?.duration ?? 0)} — ${data.session?.timestamp ? new Date(data.session.timestamp).toISOString().split("T")[0] : "N/A"}</p>

  <h2>Data Provenance</h2>
  <table>
    <tr><th>Field</th><th>Value</th></tr>
    <tr><td>System</td><td>SpectraX 1.0.0</td></tr>
    <tr><td>Data Source</td><td>on-device pose estimation pipeline</td></tr>
    <tr><td>Generated By</td><td>${safe(data.user?.displayName ?? "anonymous")}</td></tr>
    <tr><td>Generated At</td><td>${new Date().toISOString()}</td></tr>
  </table>

  <h2>Session</h2>
  <table>
    <tr><th>Field</th><th>Value</th></tr>
    <tr><td>Total Reps</td><td>${safe(data.session?.totalReps)}</td></tr>
    <tr><td>Accuracy</td><td>${data.session?.accuracy !== undefined ? Math.round(data.session.accuracy * 100) / 100 + "%" : "N/A"}</td></tr>
    <tr><td>Total Score</td><td>${safe(data.session?.totalScore)}</td></tr>
    <tr><td>Frames Captured</td><td>${safe(data.session?.totalFrames)}</td></tr>
  </table>

  <h2>Form Compliance</h2>
  ${data.biomechanics ? `<table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Reps Evaluated</td><td>${data.biomechanics.repScores.length}</td></tr>
    <tr><td>Average Score</td><td>${Math.round(data.biomechanics.averageScore * 100) / 100}%</td></tr>
    <tr><td>Score Range</td><td>${Math.round(data.biomechanics.minScore)}% – ${Math.round(data.biomechanics.maxScore)}%</td></tr>
    ${data.biomechanics.tempoRatio ? `<tr><td>Tempo Ratio</td><td>${safe(data.biomechanics.tempoRatio)}</td></tr>` : ""}
    <tr><td>Status</td><td class="${data.biomechanics.averageScore >= 70 ? "badge-pass" : "badge-fail"}">${data.biomechanics.averageScore >= 70 ? "PASS" : "FAIL"}</td></tr>
  </table>` : "<p>No biomechanics data available.</p>"}

  <h2>Error Log</h2>
  ${data.session?.mistakes && Object.keys(data.session.mistakes).length > 0 ? `<table><tr><th>Issue</th><th>Count</th></tr>
  ${Object.entries(data.session.mistakes).sort((a, b) => b[1] - a[1]).map(([msg, count]) => `<tr><td>${safe(msg)}</td><td>${count}</td></tr>`).join("")}
  </table>` : "<p>No form errors recorded.</p>"}

  <footer>
    <p>SpectraX Compliance Report · ${new Date().toISOString()} · Version 1.0</p>
    <p>This report is an audit-quality record of on-device pose analysis data.</p>
  </footer>
</body></html>`;
}

export const complianceTemplate: ReportTemplate = {
  type: "compliance",
  label: "Compliance & Audit",
  description: "Audit-ready report with data provenance, form compliance pass/fail, and structured error logs for regulatory review.",
  supportedFormats: ["json", "markdown", "html"],

  render(data: ReportData, format: ExportFormat): string {
    if (format === "json") return renderJson(data);
    if (format === "markdown") return renderMarkdown(data);
    return renderHtml(data);
  },
};
