import type { ReportTemplate, ReportData, ExportFormat } from "../../types/report";

function safe(value: unknown, fallback = "N/A"): string {
  if (value === null || value === undefined) return fallback;
  if (typeof value === "number" && !Number.isFinite(value)) return fallback;
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#x27;");
}

function fmt(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}

function pct(value: number): string {
  return `${Math.round(value)}%`;
}

function accuracyColor(accuracy: number): string {
  if (accuracy >= 90) return "#22c55e";
  if (accuracy >= 70) return "#eab308";
  return "#ef4444";
}

function renderHtml(data: ReportData): string {
  const s = data.session;
  const b = data.biomechanics;
  const accuracy = s?.accuracy ?? 0;
  const color = accuracyColor(accuracy);

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Executive Report — ${safe(s?.exerciseName)}</title>
<style>
  body { font-family: system-ui, -apple-system, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; color: #1a1a2e; background: #f8fafc; }
  h1 { font-size: 1.5rem; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; }
  h2 { font-size: 1.15rem; margin-top: 1.5rem; color: #334155; }
  .badge { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 999px; font-weight: 600; font-size: 0.85rem; color: #fff; }
  .stats { display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr)); gap: 1rem; }
  .card { background: #fff; border-radius: 0.5rem; padding: 1rem; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
  .card label { display: block; font-size: 0.75rem; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; }
  .card .value { font-size: 1.5rem; font-weight: 700; }
  .ring { width: 120px; height: 120px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 1rem auto; }
  .mistakes { list-style: none; padding: 0; }
  .mistakes li { padding: 0.35rem 0; border-bottom: 1px solid #f1f5f9; font-size: 0.9rem; }
  footer { margin-top: 2rem; font-size: 0.75rem; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 1rem; }
</style></head>
<body>
  <h1>Executive Workout Report</h1>
  <p style="color:#64748b;">${safe(s?.exerciseName)} — ${fmt(s?.duration ?? 0)}</p>

  <div class="ring" style="background:conic-gradient(${color} ${accuracy}deg, #e2e8f0 ${accuracy}deg);">
    <div style="background:#fff;width:90px;height:90px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:1.75rem;font-weight:700;color:${color};">${pct(accuracy)}</div>
  </div>

  <div class="stats">
    <div class="card"><label>Total Reps</label><div class="value">${safe(s?.totalReps)}</div></div>
    <div class="card"><label>Correct Reps</label><div class="value">${safe(s?.correctReps)}</div></div>
    <div class="card"><label>Best Streak</label><div class="value">${safe(s?.bestStreak)}</div></div>
    <div class="card"><label>Calories</label><div class="value">${safe(s?.calories)}</div></div>
    <div class="card"><label>XP Gained</label><div class="value">+${safe(s?.gainedXp)}</div></div>
    <div class="card"><label>Duration</label><div class="value">${fmt(s?.duration ?? 0)}</div></div>
  </div>

  ${b ? `<h2>Biomechanics Overview</h2>
  <div class="stats">
    <div class="card"><label>Avg Score</label><div class="value">${pct(b.averageScore)}</div></div>
    <div class="card"><label>Best Rep</label><div class="value">${pct(b.maxScore)}</div></div>
    <div class="card"><label>Worst Rep</label><div class="value">${pct(b.minScore)}</div></div>
    ${b.tempoRatio ? `<div class="card"><label>Tempo Ratio</label><div class="value" style="font-size:1rem;">${safe(b.tempoRatio)}</div></div>` : ""}
  </div>` : ""}

  ${s?.mistakes && Object.keys(s.mistakes).length > 0 ? `<h2>Form Improvement Areas</h2>
  <ul class="mistakes">${Object.entries(s.mistakes).sort((a, b) => b[1] - a[1]).map(([msg, count]) => `<li><span class="badge" style="background:#64748b;">${count}x</span> ${safe(msg)}</li>`).join("\n    ")}</ul>` : ""}

  <footer>Generated by SpectraX · ${new Date().toISOString().split("T")[0]} · Executive Summary</footer>
</body></html>`;
}

function renderMarkdown(data: ReportData): string {
  const s = data.session;
  const b = data.biomechanics;
  const accuracy = s?.accuracy ?? 0;

  const lines: string[] = [
    `# Executive Workout Report`,
    ``,
    `**Exercise:** ${safe(s?.exerciseName)}  `,
    `**Duration:** ${fmt(s?.duration ?? 0)}  `,
    `**Date:** ${s?.timestamp ? new Date(s.timestamp).toISOString().split("T")[0] : "N/A"}  `,
    ``,
    `## Accuracy: **${pct(accuracy)}**`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Total Reps | ${safe(s?.totalReps)} |`,
    `| Correct Reps | ${safe(s?.correctReps)} |`,
    `| Best Streak | ${safe(s?.bestStreak)} |`,
    `| Calories Burned | ${safe(s?.calories)} |`,
    `| XP Gained | ${safe(s?.gainedXp)} |`,
    ``,
  ];

  if (b) {
    lines.push(`## Biomechanics`, ``);
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Average Score | ${pct(b.averageScore)} |`);
    lines.push(`| Best Rep Score | ${pct(b.maxScore)} |`);
    lines.push(`| Worst Rep Score | ${pct(b.minScore)} |`);
    if (b.tempoRatio) lines.push(`| Tempo Ratio | ${safe(b.tempoRatio)} |`);
    lines.push(``);
  }

  if (s?.mistakes && Object.keys(s.mistakes).length > 0) {
    lines.push(`## Form Improvement Areas`, ``);
    for (const [msg, count] of Object.entries(s.mistakes).sort((a, b) => b[1] - a[1])) {
      lines.push(`- **${count}x** — ${safe(msg)}`);
    }
    lines.push(``);
  }

  if (s?.jumpingJackSync) {
    lines.push(`## Jumping Jack Coordination`, ``);
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Sync Score | ${safe(s.jumpingJackSync.score !== null ? s.jumpingJackSync.score + "%" : "N/A")} |`);
    lines.push(`| Lag | ${safe(s.jumpingJackSync.lagMs !== null ? s.jumpingJackSync.lagMs + "ms" : "N/A")} |`);
    lines.push(`| Confidence | ${safe(s.jumpingJackSync.confidence)} |`);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Generated by SpectraX — Executive Summary — ${new Date().toISOString().split("T")[0]}*`);

  return lines.join("\n");
}

export const executiveTemplate: ReportTemplate = {
  type: "executive",
  label: "Executive Summary",
  description: "High-level performance overview with accuracy, calorie, and XP metrics, suitable for coaches and dashboards.",
  supportedFormats: ["html", "markdown"],

  render(data: ReportData, format: ExportFormat): string {
    if (format === "markdown") return renderMarkdown(data);
    return renderHtml(data);
  },
};
